[book]
authors = ["revol-xut", "oxa", "marenz" ]
language = "en"
multilingual = false
src = "src"
title = "DVB-Dump"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
